name: Liverpool tapte varsling (manuell)

on:
  workflow_dispatch:

jobs:
  check_liverpool_history:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut repo
      uses: actions/checkout@v3

    - name: Installer Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installer axios
      run: npm install axios

    - name: Kjør Liverpool-sjekk (historikk)
      run: node check_last.js history

    - name: Send Pushcut notification
      if: success()
      run: curl "https://api.pushcut.io/R5brW4g13iCchU9EjQ0_u/notifications/Liverpool_tapte"
