name: Liverpool tapte varsling

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check_liverpool:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut repo
      uses: actions/checkout@v3

    - name: Installer Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Installer axios
      run: npm install axios

    - name: Debug (viser at workflow kjører)
      run: echo "Workflow kjører OK"

    - name: Kjør Liverpool-sjekk
      run: node check_last.js

    - name: Send Pushcut notification (hardkodet GET)
      if: success()
      run: curl "https://api.pushcut.io/R5brW4g13iCchU9EjQ0_u/notifications/Liverpool_tapte"
